### ISSUE TITLE
Add support for Angular 17

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents-ngx#108]
### **Feature Request Description**
Add compatibility with version 17 to use the new features of the framework

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by joseserrano15** [comment]
Hello and thanks for the update for angular 17.

Is it really already compatible? I have been trying to install in an Angular 17 project without success. Maybe I'm doing something wrong? I am trying with version 0.3.0-rc.0.

Thanks in advance.

**Comment by g-cheishvili** [comment]
The RC version contained incorrect peer dependencies. I created the PR and will fix that in next RC asap

**Comment by joseserrano15** [comment]
Thank you so much. Now it works perfect.
