### ISSUE TITLE
Error with "@ui5/theming-ngx"

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents-ngx#116]
### **Bug Description**
After running ng serve, an error related to "@ui5/theming-ngx" occurs, preventing the application from running.

### **Expected Behavior**
The application should run without problems

### **Steps to Reproduce**
1. Install 0.3.0-rc.1 version in an Angular 17 project
2. Run ng serve

### **Context**
- UI5 Web Components version: {1.22.0}
- UI5 Web Components for Angular version: {0.3.0-rc.1}
- Angular Version: {17.2.0}
- OS/Platform: {Ubuntu}
- Browser: {Brave}
- Affected component: {All}

### **Log Output / Stack Trace / Screenshots**
![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/68348356/ca6cfe00-0718-4379-81e7-c667436398b1)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by g-cheishvili** [comment]
Do you have @ui5/theming-ngx@0.3.0-rc.1 installed?

**Comment by joseserrano15** [comment]
No, I don't have it in my package.json. Is it necessary to install it separately? In previous versions I never had to do it.

**Comment by g-cheishvili** [comment]
It needs to be installed, if you have installed our repo via ng-add it would have been in your deps automatically I believe

**Comment by joseserrano15** [comment]
I didn't know. I installed it and it worked without problems, thank you and sorry for the inconvenience.
