### ISSUE TITLE
Problem with autocompletion in ui5-input

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents-ngx#119]
Hello, I am experiencing an error with the ui5-input.
When the field is autocompleted with information saved in the browser (username and session password for example), an error is displayed and the input does not obtain the value.
I have the input inside a reactive form and the problem only happens once the production build is generated.

`<ui5-input id="inputUser" [placeholder]="placeHolderUserInput" formControlName="user" type="Text"></ui5-input>
`

Error
![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/68348356/7c0fe48f-65b7-4778-a425-ab372700efe9)

**Comment by ilhan007** [comment]
Hello @joseserrano15 

this has been resolved on the web components side with the following change

https://github.com/SAP/ui5-webcomponents/pull/9130

In short, the browser suggestions are turned off which follows the design specs as it competes with the Input suggestions and value state popovers. This is done via `autocomplete="off"` set on the native input.

The fix in`@ui5/webcomponents`  is integrated in `@ui5/webcomponents-ngx` and available with version >= 0.3.0-rc.6.

BR,
ilhan
