### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by droshev** [SAP/ui5-webcomponents-ngx#12]
### **Steps to Reproduce**
2. ...
3. ...

### **Context**
- UI5 Web Components version: {...}
- UI5 Web Components for Angular version: {...}
- Angular Version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [x] Very High

**Comment by g-cheishvili** [comment]
I think this is resolved already
