### ISSUE TITLE
Input, Select always throws error in focusout

### ISSUE THREAD

**Issue by xianshenglu** [SAP/ui5-webcomponents-ngx#120]
### **Bug Description**
Input, Select always throws error in focusout

### **Expected Behavior**
No errors should be thrown

### **Steps to Reproduce**
1. Go to https://ui5-webcomponents-ngx.netlify.app/?path=/docs/ui5-web-components-main-input--docs&globals=backgrounds.grid:!false
2. Open the devtool
3. Focus the demo input
4. Focus out
5. You can see the errors thrown

### **Isolated Example**
https://ui5-webcomponents-ngx.netlify.app/?path=/docs/ui5-web-components-main-input--docs&globals=backgrounds.grid:!false

### **Context**
- UI5 Web Components version: your demo site version
- UI5 Web Components for Angular version: your demo site version
- Angular Version: 17
- OS/Platform: Windows
- Browser: Chrome 121.0.6167.140 (Official Build) (64-bit)
- Affected component: Input, Select

### **Log Output / Stack Trace / Screenshots**

![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/23273077/3d17072d-f0cd-4a7b-beb5-780c0644f0c8)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @xianshenglu the issue will be resolved with the following PR https://github.com/SAP/ui5-webcomponents-ngx/pull/126 and it will be soon merged
