### ISSUE TITLE
Switch always throws error in onChange.

### ISSUE THREAD

**Issue by joseserrano15** [SAP/ui5-webcomponents-ngx#121]
### **Bug Description**
Switch always throws error in onChange

### **Expected Behavior**
No errors should be thrown

### **Steps to Reproduce**
1. Go to https://ui5-webcomponents-ngx.netlify.app/?path=/docs/ui5-web-components-main-switch--docs
2. Open the devtool
3. Push any switch in the examples
4. You can see the error

### **Context**
- UI5 Web Components version: your demo site version
- UI5 Web Components for Angular version: your demo site version
- Angular Version: 17
- OS/Platform: Windows
- Browser: Brave
- Affected component: Switch

### **Log Output / Stack Trace / Screenshots**
![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/68348356/665453d7-ee49-4101-bb93-e223c7c3f189)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @joseserrano15 the issue will be resolved with https://github.com/SAP/ui5-webcomponents-ngx/pull/126 and it will be soon merged
