### ISSUE TITLE
Doc examples not working

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/ui5-webcomponents-ngx#127]
For the following components the examples in the documentation are not working:

- [ ] Busy indicator
- [ ] Color palette popover 
- [ ] Menu
- [ ] Popover
- [ ] Responsive Popover
- [ ] Dynamic Side Content
- [ ] Flexible Column Layout
- [ ] Product Switch  - last example
- [ ] Side Navigation
- [ ] View Settings Dialog
- [ ] Dialog - the dialogs don't show
- [ ] Toast - toasts don't show

**Comment by ilhan007** [comment]
Hi, yes all will be working after the PR https://github.com/SAP/ui5-webcomponents-ngx/pull/126 is merged
