### ISSUE TITLE
Date pickers can't select date

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/ui5-webcomponents-ngx#129]
The date selection is not working for
- [ ] Date Picker
- [ ] Date Range Picker
- [ ] Date Time Picker

**Comment by ilhan007** [comment]
Hi Inna, yes, I noticed the same in the currently deployed story book https://ui5-webcomponents-ngx.netlify.app/?path=/docs/ui5-web-components-main-datepicker--docs
And, it's not only for the date-* components, but for all form associated components.

It's a ngx wrapper specific issue. If you open the console you will see runtime exception `ctx._cva.onChange is not a function`. 

The issue will be resolved with the PR (opened few days ago), which is upgrading the underlying UI5 Web Components version **+ fixing this wrapper specific issue**.
