### ISSUE TITLE
NPM package creating

### ISSUE THREAD

**Issue by droshev** [SAP/ui5-webcomponents-ngx#13]
### **Feature Request Description**
Introduce an NPM package `@ui5/webcomponents-ngx`

### **Proposed Solution**
Create a CI action that pushes in NPM registry the package `@ui5/webcomponents-ngx` (we will start with this package only. if more needed, we will discuss when, what, where to create)

### **Priority**
- [x] Medium

**Comment by g-cheishvili** [comment]
This is done
