### ISSUE TITLE
Register tokens for npm, gh and others

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents-ngx#2]
Need 
`NPM_TOKEN` for publishing the library
`GH_TOKEN` for releases on gh side
`GH_NAME` and `GH_EMAIL`
`NX_CLOUD_AUTH_TOKEN` for Nx cloud

**Comment by petermuessig** [comment]
`NPM_TOKEN` repository secret has been created!

**Comment by g-cheishvili** [comment]
All the needed tokens are done for now
