### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by droshev** [SAP/ui5-webcomponents-ngx#21]
### **Feature Request Description**
We need to define options to provide configuration to the Angular framework layer, UI5 Web Components and Fundamental Styles. How to do this?

- [x] Language
- [x] Theme
- [x] Content Density
- [x] Formatting Locale
- [x] Calendar

### **Proposed Solution**
- [x] TBD after the research

### **Priority**
- [x] Medium

**Comment by N1XUS** [comment]
Theme is covered with #9
