### ISSUE TITLE
Standardize available themes

### ISSUE THREAD

**Issue by N1XUS** [SAP/ui5-webcomponents-ngx#24]
### **Feature Request Description**

Currently, we don't have one source of truth when it comes to the list of available themes:
- sap-theming package exposes all themes that can be used in application: 
![image](https://user-images.githubusercontent.com/6586561/216544556-34bd3267-9597-4566-9e34-2c99dc224472.png)

- ui5-webcomponents-theming package exposes all themes except for `sap_fiori_3_light_dark`:
![image](https://user-images.githubusercontent.com/6586561/216544447-4087be61-8592-40d2-a930-0ef42987ff8a.png)
- fundamental-styles package exposes new themes (belize is skipped):
![image](https://user-images.githubusercontent.com/6586561/216544741-7d276d77-2e1d-4695-a7a7-72ead15f3bf3.png)

With such different lists of supported themes it becomes hard to actually sync theming across multiple libs in one app.

### **Proposed Solution**
A clear and concise description of the solution you would like to have. -->
Theming package generator should know which set of themes can be used with components used in app.
I mean, if we have ui5-webcomponents AND fundamental-styles, we should exclude belize and sap_fiori_3_light_dark since these themes are not supported by both libraries at the same time.
On the other hand, if application has only ui5-webcomponents, we should not restrict belize theme.
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by g-cheishvili** [comment]
The best way would be that provider gives list of available themes and then the main service queries both(or more) and understands which ones are available for current application, given the providers
