### ISSUE TITLE
Ng-add does not add ui5 theming provider

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/ui5-webcomponents-ngx#31]
### **Bug Description**
When you install the package with ng add and use theming, it should also add theming provider service module in app.module alongside theming module

### **Expected Behavior**
Working theming

**Comment by N1XUS** [comment]
@g-cheishvili actually, schematics are importing Ui5ThemingModule which contains instance of theming service, so providing the service itself is not needed anymore: https://github.com/SAP/ui5-webcomponents-ngx/blob/main/libs/ui5-angular-theming/src/ui5-theming.module.ts#L15
