### ISSUE TITLE
Progress indicators cannot be given accessible names

### ISSUE THREAD

**Issue by bpan4** [SAP/ui5-webcomponents-ngx#50]
### **Bug Description**

There is no way to set accessible names for ```ui5-progress-indicator``` elements.

### **Expected Behavior**

There should be a way to set an accessible name for ```ui5-progress-indicator``` elements.

### **Steps to Reproduce**
1. Create a ```ui5-progress-indicator``` element.
2. Use either a screen reader or generate a [Lighthouse](https://github.com/GoogleChrome/lighthouse) report
3. Notice that the ```ui5-progress-indicator``` item is reported to be without an accessible name that would provide more details on its function

### **Isolated Example**

```
<ui5-progress-indicator 
   display-value="Late" 
   value-state="Error" 
   [value]="20" 
   aria-label="20% of flights have been late">
</ui5-progress-indicator>
```

### **Context**
- UI5 Web Components version: 1.11.0
- UI5 Web Components for Angular version: 0.1.0-rc.0
- Angular Version: 15
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-progress-indicator

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/80479238/227028276-26c7e884-086d-4d22-a5fb-ccff7b323fcf.png)
Part of the report generated by Lighthouse.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @bpan4 we did not update you timely, but the ProgressIndicator has **accessibleName** property as requested.

BR,
ilhan
