### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by gedlbauer** [SAP/ui5-webcomponents-ngx#62]
### **Bug Description**
The package `@ui5/theming-ngx` is missing from the projects dependencies. To use `@ui5/webcomponents-ngx`, you need to manually install the mentioned package.

### **Expected Behavior**
`@ui5/theming-ngx` should be installed automatically when installing `@ui5/webcomponents-ngx`

### **Steps to Reproduce**
1. install  `@ui5/theming-ngx`
2. try to use it

### **Context**
- UI5 Web Components for Angular version: 0.1.1
- Angular Version: 15.2.0
- OS/Platform: Windows

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by droshev** [comment]
@gedlbauer Did you try running `ng add @ui5/webcomponents-ngx`? Our CLI will do the rest?

**Comment by ilhan007** [comment]
Hello @gedlbauer with @ui5/webcomponents-ngx 0.3.0-rc.9, you need to only 
```sh
npm i @ui5/webcomponents-ngx
```

and then

```sh
ng serve
```

and everything works without additional steps from your side as the `@ui5/theming-ngx` is brought along `@ui5/webcomponents-ngx`

BR,
ilhan
