### ISSUE TITLE
RangeSlider min and max value labels don't update if the respective values change

### ISSUE THREAD

**Issue by ynnckth** [SAP/ui5-webcomponents-ngx#82]
## Bug Description
When using the ui5-range-slider component with dynamic min and max values, the labels of the range slider do not reflect the updated values. 

## Expected Behaviour
If I bind the input properties "min" and "max" of the range slider to properties that change dynamically, the labels of the range slider should reflect the new min and max values. However, the labels don't change and keep the initial values instead.

## Steps to Reproduce
Create a component containing a ui5-range-slider element. 
Add two properties `minValue` and `maxValue` of type number to your component.
Reference these values in the range slider such as 
`<ui5-range-slider [min]="minValue" [max]="maxValue" ...></ui5-range-slider>`
Add for example a button that increments `minValue` and `maxValue` of your component.
Observe that the labels of the range slider do not update to reflect the new minimum and maximum range values.

Minimal example sandbox: 
> https://codesandbox.io/p/sandbox/affectionate-poitras-7pv7vy

Context:
UI5 Web Components for Angular version: 0.2.2
Angular Version: 16
OS/Platform: MacOS
Browser: Chrome
Affected component: ui5-range-slider

**Comment by veith** [comment]
Look at issue https://github.com/SAP/ui5-webcomponents/issues/7628 this will solve your problem.

**Comment by ilhan007** [comment]
Hello @ynnckth this is fixed last year, however we did not update you timely, sorry for that. The issue with the RangeSlider is resolved - tested with 0.3.0-rc.8.
