### ISSUE TITLE
Select: No FormControl support 

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents-ngx#93]
Created the issue on behalf of SAP Build Process Automation:
Select - FormControl support is missing.

### **Steps to Reproduce**
2. ...
3. ...

### **Context**
- UI5 Web Components version: {...}
- UI5 Web Components for Angular version: {...}
- Angular Version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hello @droshev this is one of the latest issues raised. Meanwhile I will ask the authors for more information. Thank you.

**Comment by timogeib** [comment]
FormControl not working at all -> No value accessor for form control error in console
![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/137267915/a6878b01-9be8-4d22-9d7c-0c612fe4932b)
![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/137267915/41d489c4-5585-4420-b8a4-4df17e300d43)

**Comment by ilhan007** [comment]
Hello @mikerodonnell89 @g-cheishvili 

The FormControl support of the Select directive should be fixed if you update the ui5-webcomponents-ngx wrappers to the latest ui5-webcomponents as in the latest version we introduced a "value" property to the Select web component (that is marked as formProperty), so that the generated wrapper will extend GVA and the default setters and getters that rely on having a "value" property will work as we added "value" property to the Select web component

Actually I tried to update but there are some build issues to fix:
https://github.com/SAP/ui5-webcomponents-ngx/pull/103
