### ISSUE TITLE
RadioButton: No FormControl support

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents-ngx#94]
Created the issue on behalf of SAP Build Process Automation:
RadioButton - FormControl support is missing.

### **Steps to Reproduce**
2. ...
3. ...

### **Context**
- UI5 Web Components version: {...}
- UI5 Web Components for Angular version: {...}
- Angular Version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by timogeib** [comment]
Please check the CODE example in
https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-radio-button--docs
ui5-radio-button are nested, Option 2 is there multiple times.
Added example to https://github.tools.sap/I555913/ui5-webcomponents-sandbox for issue 94
FormControl value is set to "true" as soon as a radio is selected, not the selected option. Default form FormControl is not set.
![image](https://github.com/SAP/ui5-webcomponents-ngx/assets/137267915/b4f32854-55d8-4f68-904a-22769c62ef75)
