### ISSUE TITLE
Reactive Forms: "touched" not updated for all form controls

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents-ngx#95]
Created the issue on behalf of SAP Build Process Automation:
"Reactive Forms: On nearly all components we need to set value and control.touched manually to trigger validations"

### **Steps to Reproduce**
2. ...
3. ...

### **Context**
- UI5 Web Components version: {...}
- UI5 Web Components for Angular version: {...}
- Angular Version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by ilhan007** [comment]
Hi @deno. I will ask the authors for more information and context.

**Comment by timogeib** [comment]
on all the formcontrols "touched" is not updated leading to the problem with validation described in #7776 already
